V2.34.6c: Remove temperature param - unsupported by current Azure model (o-series)
Error: 'temperature' does not support 0.3 with this model. Only the default (1) value is supported.
The GPT5_MODEL env var is set to an o-series model which doesn't support temperature.